Registro, Login y Logout
adoptadiCOs/adoptadicos.github.io pull request #53
Opened 2022-05-16 22:29 UTC by xzebra

2022-05-18 18:57 UTC, Leticia-23 requested changes
- Si se pone mal las contraseñas o se cambia algún campo, luego aunque esté todo completado lo coge como que no y hay que volver a escribir todos. Esto no sé si realmente se puede hacer algo o es por los state y setState.
- Cuando ha habido algún fallo y luego haces correctamente se quedan los mensajes del error y el de ok registro. 
- En login hay que hacer como en registro si el problema es con el correo por ejemplo, nos llega el mensaje de error de backend pero no se indica de ninguna manera al usuario. Deberíamos de indicarle para que pueda saber qué está ocurriendo. 
- Habrá que hablar con backend para que haya una foto por defecto de perfil que se pueda cargar. 

He visto estas cosas, dime qué opinas. Si algo prefieres que lo mire yo o que haga el merge y cuando podamos añadir signup y login con rrss modificamos estas cosas.

2022-05-18 21:17 UTC, xzebra commented
Vale ya mirare para arreglar esto cuando pueda.

> ... cuando podamos añadir signup y login con rrss modificamos estas cosas.

El problema sera que todas las PRs a posteriori dependen de la sesión (que está implementada en esta). Y como hagamos algún cambio va a haber que sincronizarlas todas con esta jajaja.

Así que yo las RRSS las haría en una aparte.

2022-05-19 10:34 UTC, Leticia-23 commented
Sí a eso me refería, de tener en cuenta esas cosas, y mergear igualmente para poder tener el inicio de sesión y registro para el resto de cosas. Pero quería saber qué opinabas.
Mergeo y lo miraremos en sigueintes PR.

2022-05-19 10:35 UTC, Leticia-23 approved these changes

2022-05-19 10:35 UTC, merged